### ISSUE TITLE
iOS 64-bit Version?

### ISSUE THREAD

**Issue by chrishaff** [pegli/ti_touchdb#90]
Apple will require 64-bit on Feb 1, 2015 and Appcelerator released their guidance on how to do this.  What the schedule is for this (awesome) module?

Thanks!

**Comment by pegli** [comment]
I've added a build of the iOS version of the library to the 1.2.1 pre-release

  https://github.com/pegli/ti_touchdb/releases/tag/1.2.1

Let me know if you run into any problems with that build.

**Comment by pegli** [comment]
Version 1.2.1 and later support 64-bit iOS versions, so I'm closing this issue.
